stages:
  - build
  - test
  - docker-build

build:
  stage: build
  image: node
  script: 
    - echo "Start building App"
    - npm install
    - npm build
    - echo "Build successfully!"
  artifacts:
    expire_in: 1 hour
    paths:
      - build
      - node_modules/

test_master_branch:
  stage: test
  image: node
  script:
    - echo "Testing App"
    - CI=true npm test
    - echo "Test successfully!"
  only:
    - master
test_dev_branch:
  stage: test
  image: node
  only:
   - dev
  script:
    - echo "Testing App"
    - CI=true npm test
    - echo "Test successfully!"
test_feature_branch:
  stage: test
  image: node
  only:
    - /^issue-.*$/
  script:
    - echo "Testing App"
    - CI=true npm test
    - echo "Test successfully!"
    - git push -o merge_request.create -o merge_request.target=dev -o merge_request.merge_when_pipeline_succeeds

docker-build:
  stage: docker-build
  image: docker:latest
  services: 
    - name: docker:19.03.8-dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"